[env:esp32-s3]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DXPOWERS_CHIP_AXP2101
    -DARDUINO_USB_CDC_ON_BOOT=0
    -Iinclude
    -DCONFIG_FREERTOS_ENABLE_STATIC_TASK_STACK_CHECK=1

board_build.partitions = default_16MB.csv

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.3
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.0
    lewisxhe/XPowersLib@^0.2.0

upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
upload_speed = 921600
